import React from 'react'
import { ORG } from '@/data/outlets'
import { fmtDateTime } from '@/lib/format'
import type { ReportCtx, ReportResult, RCol, Row } from './types'
import { fmtCell } from './gen'
import { computeTotals } from './totals'

export function A4Page({ children }: { children: React.ReactNode }) {
  return <div className="w-[210mm] max-w-full bg-white px-[12mm] py-[10mm] text-[10.5px] leading-snug text-slate-800">{children}</div>
}

export function A4Header({ ctx, title, subtitle, user }: { ctx: ReportCtx; title: string; subtitle?: string; user?: string }) {
  const outletLabel = ctx.outlets.length === 1 ? ctx.outlets[0].name : `All Outlets (${ctx.outlets.map((o) => o.short).join(', ')})`
  return (
    <div className="mb-4 border-b-2 border-slate-800 pb-3">
      <div className="flex items-start justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <span className="flex size-8 items-center justify-center rounded-md bg-[#0f2a4a] text-[13px] font-bold text-white">GK</span>
            <div>
              <p className="text-[15px] font-bold tracking-tight text-slate-900">{ORG.name}</p>
              <p className="text-[9.5px] text-slate-500">{ORG.legal} · GSTIN {ctx.outlets.length === 1 ? ctx.outlets[0].gstin : ORG.gstin}</p>
            </div>
          </div>
          <p className="mt-1 text-[9.5px] text-slate-500">{ctx.outlets.length === 1 ? ctx.outlets[0].address : ORG.hq}</p>
        </div>
        <div className="text-right">
          <p className="text-[14px] font-bold uppercase tracking-wide text-slate-900">{title}</p>
          {subtitle && <p className="text-[9.5px] text-slate-500">{subtitle}</p>}
        </div>
      </div>
      <div className="mt-3 grid grid-cols-4 gap-3 rounded bg-slate-50 px-3 py-2 text-[9.5px]">
        <div><p className="text-slate-400">Outlet</p><p className="font-semibold text-slate-800">{outletLabel}</p></div>
        <div><p className="text-slate-400">Period</p><p className="font-semibold text-slate-800">{ctx.rangeLabel}</p></div>
        <div><p className="text-slate-400">Generated at</p><p className="font-semibold text-slate-800">{fmtDateTime(Date.now())}</p></div>
        <div><p className="text-slate-400">Generated by</p><p className="font-semibold text-slate-800">{user ?? 'System'}</p></div>
      </div>
    </div>
  )
}

export function A4Footer() {
  return (
    <div className="mt-6 flex items-end justify-between border-t border-slate-200 pt-3 text-[9px] text-slate-400">
      <span>System generated report · RestroFlow Enterprise · {ORG.website}</span>
      <div className="flex gap-10">
        <span className="border-t border-slate-400 px-4 pt-1 text-slate-500">Prepared by</span>
        <span className="border-t border-slate-400 px-4 pt-1 text-slate-500">Verified by</span>
      </div>
    </div>
  )
}

export function A4Table({ columns, rows, totals, maxRows = 250 }: { columns: RCol[]; rows: Row[]; totals?: Record<string, string> | null; maxRows?: number }) {
  const shown = rows.slice(0, maxRows)
  return (
    <>
      <table className="w-full border-collapse text-[9.5px]">
        <thead>
          <tr className="bg-slate-800 text-white">
            {columns.map((c) => <th key={c.key} className={`px-1.5 py-1 font-semibold ${c.align === 'right' ? 'text-right' : c.align === 'center' ? 'text-center' : 'text-left'}`}>{c.header}</th>)}
          </tr>
        </thead>
        <tbody>
          {shown.map((r, i) => (
            <tr key={r.id} className={i % 2 ? 'bg-slate-50' : ''}>
              {columns.map((c) => <td key={c.key} className={`border-b border-slate-100 px-1.5 py-[3px] ${c.align === 'right' ? 'text-right tabular' : c.align === 'center' ? 'text-center' : ''}`}>{fmtCell(r[c.key], c.fmt)}</td>)}
            </tr>
          ))}
        </tbody>
        {totals && (
          <tfoot>
            <tr className="border-t-2 border-slate-800 font-bold">
              {columns.map((c, i) => <td key={c.key} className={`px-1.5 py-1 ${c.align === 'right' ? 'text-right tabular' : ''}`}>{i === 0 ? 'TOTAL' : totals[c.key] ?? ''}</td>)}
            </tr>
          </tfoot>
        )}
      </table>
      {rows.length > maxRows && <p className="mt-1 text-[9px] italic text-slate-400">Showing first {maxRows} of {rows.length} rows — export to Excel for the complete register.</p>}
    </>
  )
}

export function ReportDocument({ ctx, title, result, user }: { ctx: ReportCtx; title: string; result: ReportResult; user?: string }) {
  const totals = computeTotals(result.columns, result.rows)
  return (
    <A4Page>
      <A4Header ctx={ctx} title={title} user={user} subtitle={`${result.rows.length} records`} />
      {result.kpis.length > 0 && (
        <div className="mb-4 grid grid-cols-4 gap-2">
          {result.kpis.slice(0, 8).map((k) => (
            <div key={k.label} className="rounded border border-slate-200 px-2 py-1.5">
              <p className="text-[8.5px] uppercase tracking-wide text-slate-400">{k.label}</p>
              <p className="text-[12px] font-bold text-slate-900">{k.value}</p>
              {k.sub && <p className="text-[8.5px] text-slate-400">{k.sub}</p>}
            </div>
          ))}
        </div>
      )}
      <A4Table columns={result.columns} rows={result.rows} totals={totals} />
      {result.note && <p className="mt-2 text-[9px] text-slate-500">Note: {result.note}</p>}
      <A4Footer />
    </A4Page>
  )
}
